### PR TITLE
Added ChefSpec custom matchers and examples

### PR DESCRIPTION
**Pull request by mreeves1**
### Description

Added ChefSpec custom matchers and examples

### Issues Resolved

n/a

### Check List
- [x] All tests pass. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD
- [ ] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] The CLA has been signed. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD

### CODE REVIEW

**Comment by mreeves1** [comment]
One kitchen test with default-debian-79 seemed to hang but don't see how this could be the cause.

**Comment by tas50** [comment]
Normally we handle the version bump but I'd do the same bump anyways so I won't have you undo it.  Thanks for adding this.  It'll be very handy for users.

**Comment by mreeves1** [comment]
Cool, thanks! Happy to help. I noticed the [travis tests failed](https://travis-ci.org/chef-cookbooks/bluepill/builds). It looked like the last kitchen test with default-debian-79 just hung. Need any help looking into that?

**Comment by tas50** [comment]
The integration tests in travis are very handy, but not very reliable.  We have to kick them a lot to get them to finish.

**Pull request merged**
